openapi: 3.0.0
info:
  contact:
    email: mail@worldnewsapi.com
    name: David Urbansky
  description: The world's news wrapped into a single API.
  termsOfService: https://worldnewsapi.com/terms
  title: World News API
  version: 1.1.1
servers:
- url: https://api.worldnewsapi.com
security:
- apiKey: []
- headerApiKey: []
paths:
  /search-news:
    get:
      deprecated: false
      description: "Search and filter news by text, date, location, language, and\
        \ more. The API returns a list of news articles matching the given criteria.\
        \ You can set as many filtering parameters as you like, but you have to set\
        \ at least one, e.g. text or language."
      externalDocs:
        description: Read entire docs
        url: https://worldnewsapi.com/docs/search-news/
      operationId: searchNews
      parameters:
      - description: "The text to match in the news content (at least 3 characters).\
          \ By default all query terms are expected, you can use an uppercase OR to\
          \ search for any terms, e.g. tesla OR ford"
        explode: false
        in: query
        name: text
        required: false
        schema:
          example: tesla
          maxLength: 300
          pattern: "."
          type: string
        style: form
      - description: A comma-separated list of ISO 3166 country codes from which the
          news should originate.
        explode: false
        in: query
        name: source-countries
        required: false
        schema:
          example: "us,uk"
          maxLength: 100
          pattern: "."
          type: string
        style: form
      - description: The ISO 6391 language code of the news.
        explode: false
        in: query
        name: language
        required: false
        schema:
          example: en
          maxLength: 2
          pattern: "."
          type: string
        style: form
      - description: "The minimal sentiment of the news in range [-1,1]."
        explode: false
        in: query
        name: min-sentiment
        required: false
        schema:
          example: -0.8
          format: double
          maximum: 1
          minimum: -1
          type: number
        style: form
      - description: "The maximal sentiment of the news in range [-1,1]."
        explode: false
        in: query
        name: max-sentiment
        required: false
        schema:
          example: 0.8
          format: double
          maximum: 1
          minimum: -1
          type: number
        style: form
      - description: The news must have been published after this date.
        explode: false
        in: query
        name: earliest-publish-date
        required: false
        schema:
          example: 2022-04-22 16:12:35
          maxLength: 19
          pattern: "."
          type: string
        style: form
      - description: The news must have been published before this date.
        explode: false
        in: query
        name: latest-publish-date
        required: false
        schema:
          example: 2022-04-22 16:12:35
          maxLength: 19
          pattern: "."
          type: string
        style: form
      - description: A comma-separated list of news sources from which the news should
          originate.
        explode: false
        in: query
        name: news-sources
        required: false
        schema:
          example: https://www.bbc.co.uk
          maxLength: 10000
          pattern: "."
          type: string
        style: form
      - description: A comma-separated list of author names. Only news from any of
          the given authors will be returned.
        explode: false
        in: query
        name: authors
        required: false
        schema:
          example: John Doe
          maxLength: 300
          pattern: "."
          type: string
        style: form
      - description: Filter news by entities (see semantic types).
        explode: false
        in: query
        name: entities
        required: false
        schema:
          example: ORG:Tesla
          maxLength: 10000
          pattern: "."
          type: string
        style: form
      - description: "Filter news by radius around a certain location. Format is \"\
          latitude,longitude,radius in kilometers\". Radius must be between 1 and\
          \ 100 kilometers."
        explode: false
        in: query
        name: location-filter
        required: false
        schema:
          example: "51.050407, 13.737262, 20"
          maxLength: 100
          pattern: "."
          type: string
        style: form
      - description: The sorting criteria (publish-time or sentiment).
        explode: false
        in: query
        name: sort
        required: false
        schema:
          example: publish-time
          maxLength: 100
          pattern: "."
          type: string
        style: form
      - description: Whether to sort ascending or descending (ASC or DESC).
        explode: false
        in: query
        name: sort-direction
        required: false
        schema:
          example: ASC
          maxLength: 4
          pattern: "."
          type: string
        style: form
      - description: "The number of news to skip in range [0,10000]"
        explode: false
        in: query
        name: offset
        required: false
        schema:
          example: 0
          format: int32
          maximum: 10000
          minimum: 0
          type: integer
        style: form
      - description: "The number of news to return in range [1,100]"
        explode: false
        in: query
        name: number
        required: false
        schema:
          example: 10
          format: int32
          maximum: 100
          minimum: 1
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              examples:
                Response:
                  value:
                    offset: 0
                    number: 10
                    available: 83
                    news:
                    - summary: "Tesla CEO Elon Musk has revealed new details about\
                        \ the upcoming Cybertruck electric pickup truck. According\
                        \ to Musk, its initial production will begin with a four-motor\
                        \ variant."
                      image: https://internetprotocol.co/content/images/2021/12/Tesla-to-Release-a-Four-Motor-Version-of-Cybertruck.png
                      sentiment: 0.712523
                      source_country: co
                      language: en
                      id: 28
                      text: "Tesla CEO Elon Musk has revealed new details about the\
                        \ upcoming Cybertruck electric pickup truck, the mass production\
                        \ of which was delayed until 2023 because of the lack of components\
                        \ and a lot of complex technologies that need to be scaled\
                        \ up. According to Musk, the initial production of the electric\
                        \ pickup truck will begin with a four-motor variant with “\
                        independent, ultra fast response torque control of each wheel,”\
                        \ the tweet reads. In response, Twitter users asked if the\
                        \ Cybertruck could turn like a tank. Musk said that thanks\
                        \ to both the rear and front wheel steer, the electric truck\
                        \ will not only be able to turn like a tank, but also drive\
                        \ diagonally like a crab. According to Electrek, this change\
                        \ could be Tesla's reaction to what its competitors do. Since\
                        \ the introduction of Tesla’s novelty, the market for electric\
                        \ pickup trucks has significantly evolved. Currently, one\
                        \ electric pickup on the market can turn like a tank – the\
                        \ Rivian R1T, while GMC's Hummer EV can drive diagonally.\
                        \ Following the announcement of Tesla Cybertruck in 2019,\
                        \ the company announced three configurations of the pickup\
                        \ truck: the entry-level model with one motor, the one with\
                        \ two motors, and the one with three. Rumor has it that the\
                        \ company intends to abandon the single-motor version altogether.\
                        \ In this case, Tesla Cybertruck will be sold with two, three,\
                        \ and four motors. Musk has promised to provide an update\
                        \ on the pickup's roadmap on the next earnings call. The production\
                        \ of Tesla Cybertruck is expected to begin at the end of 2022,\
                        \ and its mass production is slated to start in 2023."
                      title: Tesla to Release a Four-Motor Version of Cybertruck
                      publish_date: 2022-09-30 01:07:48
                      url: https://internetprotocol.co/hitech/2021/12/07/tesla-to-release-a-four-motor-cybertruck/
                      authors:
                      - Iwan Stone
                      - Zahna Eklund
              schema:
                $ref: '#/components/schemas/searchNews_200_response'
          description: Success
        "401":
          description: Unauthorized
        "402":
          description: Payment Required
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "406":
          description: Not Acceptable
        "429":
          description: Too Many Requests
      summary: Search News
      tags:
      - News
  /top-news:
    get:
      deprecated: false
      description: Get the top news from a country in a language for a specific date.
        The top news are clustered from multiple sources in the given country. The
        more news in a cluster the higher the cluster is ranked.
      externalDocs:
        description: Read entire docs
        url: https://worldnewsapi.com/docs/top-news/
      operationId: topNews
      parameters:
      - description: The ISO 3166 country code of the country for which top news should
          be retrieved.
        explode: false
        in: query
        name: source-country
        required: true
        schema:
          example: us
          maxLength: 2
          pattern: "."
          type: string
        style: form
      - description: The ISO 6391 language code of the top news. The language must
          be one spoken in the source-country.
        explode: false
        in: query
        name: language
        required: true
        schema:
          example: en
          maxLength: 2
          pattern: "."
          type: string
        style: form
      - description: "The date for which the top news should be retrieved. If no date\
          \ is given, the current day is assumed."
        explode: false
        in: query
        name: date
        required: false
        schema:
          example: 2024-05-30
          maxLength: 10
          pattern: "."
          type: string
        style: form
      - description: "Whether to only return basic information such as id, title,\
          \ and url of the news."
        explode: false
        in: query
        name: headlines-only
        required: false
        schema:
          example: false
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              examples:
                Response:
                  value:
                    top_news:
                    - news:
                      - summary: '...'
                        image: https://politicalwire.com/wp-content/uploads/2018/02/PW-podcast-logo.jpg
                        id: 224767206
                        text: '...'
                        title: Jury to Begin Deliberations In Trump Trial
                        publish_date: 2024-05-29 00:10:48
                        url: https://politicalwire.com/2024/05/28/jury-to-begin-deliberations-in-trump-trial/
                        authors: []
                      - summary: '...'
                        image: https://dims.apnews.com/dims4/default/3446536/2147483647/strip/true/crop/6195x3485+0+323/resize/1440x810!/quality/90/?url=https%3A%2F%2Fassets.apnews.com%2Fec%2Fd5%2Ff56fdc38f86e38b6217b50083d19%2Fd5ef4afe1cb64825be1349de8fd40df0
                        id: 224839780
                        text: '...'
                        title: Jury in Donald Trump's hush money case to begin deliberations
                        publish_date: 2024-05-29 04:30:08
                        url: https://apnews.com/article/trump-trial-deliberations-jury-judge-verdict-390f045e9e8a37f069e82576edd7a842
                        authors: []
                      - summary: '...'
                        image: https://whdh.com/wp-content/uploads/sites/3/2024/05/WHDH_2024-05-27_15h27-33-cover.jpg?quality=60&strip=color
                        id: 224936214
                        text: '...'
                        title: Jury in Trump's hush money case to begin deliberations
                          after hearing instructions from judge
                        publish_date: 2024-05-29 08:47:26
                        url: https://whdh.com/news/jury-in-trumps-hush-money-case-to-begin-deliberations-after-hearing-instructions-from-judge/
                        authors: []
                      - summary: '...'
                        image: https://assets3.cbsnewsstatic.com/hub/i/r/2024/05/29/66524a85-576c-4c40-94ba-cfb04cbb7950/thumbnail/1200x630g3/d2d9c8ea35b659db292c371bdc0a47e8/gettyimages-2154550679.jpg?v=c5044be0004eac09882c007ac02fef6d
                        id: 224956968
                        text: '...'
                        video: https://prod.vodvideo.cbsnews.com/cbsnews/vr/hls/2942696_hls/master.m3u8
                        title: Trump trial jury set to begin deliberating verdict
                          today after judge issues instructions
                        publish_date: 2024-05-29 10:00:18
                        url: https://www.cbsnews.com/live-updates/trump-trial-verdict-jury-deliberations-judge-instructions/
                        authors: []
                      - summary: '...'
                        image: https://static01.nyt.com/images/2024/05/29/multimedia/29trump-trial-pinned-qzmh/29trump-trial-pinned-qzmh-facebookJumbo-v2.jpg
                        id: 224957034
                        text: '...'
                        title: Jury in Trump’s Hush-Money Trial to Begin Deliberations
                          on Wednesday
                        publish_date: 2024-05-29 10:12:08
                        url: https://www.nytimes.com/2024/05/29/nyregion/trump-trial-jury-charges.html
                        authors: []
                      - summary: '...'
                        image: https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2024/05/931/524/judge-trump.png?ve=1&tl=1
                        id: 224961802
                        text: '...'
                        title: Jury to begin deliberations in Trump trial and more
                          top headlines
                        publish_date: 2024-05-29 10:22:36
                        url: https://www.foxnews.com/us/judge-outline-framework-jury-trial-decide-trumps-fate-more-top-headlines
                        authors: []
                    - news:
                      - image: https://cdn.vox-cdn.com/thumbor/WBEMdSSOD_jHJGnNV7hLX88zANk=/0x444:5601x3376/fit-in/1200x630/cdn.vox-cdn.com/uploads/chorus_asset/file/25469085/2152809074.jpg
                        id: 225109966
                        text: '...'
                        title: Scottie Scheffler PGA Championship charges set to get
                          dropped
                        publish_date: 2024-05-29 15:24:34
                        url: https://www.sbnation.com/golf/2024/5/29/24167024/scottie-scheffler-pga-championship-louisville-police-drop-charges
                        authors: []
                      - summary: '...'
                        image: https://www.pilotonline.com/wp-content/uploads/2024/05/Scheffler_Arrest_Golf_86723_6d56d8.jpg?w=1024
                        id: 225118216
                        text: '...'
                        title: Charges against world’s top golfer Scottie Scheffler
                          dropped after arrest outside PGA Championship
                        publish_date: 2024-05-29 17:05:55
                        url: https://www.pilotonline.com/2024/05/29/charges-against-worlds-top-golfer-scottie-scheffler-dropped-after-arrest-outside-pga-championship/
                        authors: []
                      - summary: '...'
                        image: https://www.twincities.com/wp-content/uploads/2024/05/Scheffler_Arrest_Golf_86723_6d56d8.jpg?w=1024
                        id: 225118304
                        text: '...'
                        title: Charges against world’s top golfer Scottie Scheffler
                          dropped after arrest outside PGA Championship
                        publish_date: 2024-05-29 17:05:55
                        url: https://www.twincities.com/2024/05/29/charges-against-worlds-top-golfer-scottie-scheffler-dropped-after-arrest-outside-pga-championship/
                        authors: []
                      - summary: '...'
                        image: https://wsvn.com/wp-content/uploads/sites/2/2024/04/240414_Scottie_Scheffler.jpg?quality=60&strip=color
                        id: 225119550
                        text: '...'
                        title: Charges against world's top golfer Scottie Scheffler
                          dropped after arrest outside PGA Championship
                        publish_date: 2024-05-29 17:10:09
                        url: https://wsvn.com/sports/charges-against-worlds-top-golfer-scottie-scheffler-dropped-after-arrest-outside-pga-championship/
                        authors: []
                    - news:
                      - summary: '...'
                        image: https://media.nbcwashington.com/2019/09/AP163564666366.jpg?quality=85&strip=all&fit=722%2C406
                        id: 225012756
                        text: '...'
                        title: Pandas to return to DC's National Zoo
                        publish_date: 2024-05-29 12:37:10
                        url: https://www.nbcwashington.com/news/local/national-zoo-expected-to-make-announcement-about-panda-program/3627045/
                        authors: []
                      - summary: '...'
                        image: https://dims.apnews.com/dims4/default/1f5b9aa/2147483647/strip/true/crop/3382x1902+0+176/resize/1440x810!/quality/90/?url=https%3A%2F%2Fassets.apnews.com%2Fc4%2F1e%2F69094cc265243956d243348db814%2F71b160bbb0204eb594474a4934fb0df6
                        id: 225017360
                        text: '...'
                        title: Giant pandas are returning to D.C.'s National Zoo
                        publish_date: 2024-05-29 12:51:08
                        url: https://apnews.com/article/giant-pandas-washington-zoo-china-764f8016d98c01ab579bdbb6dcc3dd6b
                        authors: []
                      - summary: '...'
                        image: https://www.baltimoresun.com/wp-content/uploads/2024/05/Giant_Pandas_89303.jpg?w=1024
                        id: 225017634
                        text: '...'
                        title: 2 new giant pandas are returning to Washington’s National
                          Zoo from China by the end of the year
                        publish_date: 2024-05-29 12:52:08
                        url: https://www.baltimoresun.com/2024/05/29/2-new-giant-pandas-are-returning-to-washingtons-national-zoo-from-china-by-the-end-of-the-year/
                        authors: []
                    language: en
                    country: us
              schema:
                $ref: '#/components/schemas/topNews_200_response'
          description: Success
        "401":
          description: Unauthorized
        "402":
          description: Payment Required
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "406":
          description: Not Acceptable
        "429":
          description: Too Many Requests
      summary: Top News
      tags:
      - News
  /extract-news:
    get:
      deprecated: false
      description: "Extract a news article from a website to a well structure JSON\
        \ object. The API will return the title, text, URL, image, publish date, author,\
        \ language, source country, and sentiment of the news article."
      externalDocs:
        description: Read entire docs
        url: https://worldnewsapi.com/docs/extract-news/
      operationId: extractNews
      parameters:
      - description: The url of the news.
        explode: false
        in: query
        name: url
        required: true
        schema:
          example: https://www.bbc.com/news/world-us-canada-59340789
          maxLength: 1000
          pattern: "."
          type: string
        style: form
      - description: Whether to analyze the news (extract entities etc.)
        explode: false
        in: query
        name: analyze
        required: true
        schema:
          example: true
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              examples:
                Response:
                  value:
                    title: Tesla to Release a Four-Motor Version of Cybertruck
                    text: "Tesla CEO Elon Musk has revealed new details about the\
                      \ upcoming Cybertruck electric pickup truck, the mass production\
                      \ of which was delayed until 2023 because of the lack of components\
                      \ and a lot of complex technologies that need to be scaled up.\
                      \ According to Musk, the initial production of the electric\
                      \ pickup truck will begin with a four-motor variant with “independent,\
                      \ ultra fast response torque control of each wheel,” the tweet\
                      \ reads. In response, Twitter users asked if the Cybertruck\
                      \ could turn like a tank. Musk said that thanks to both the\
                      \ rear and front wheel steer, the electric truck will not only\
                      \ be able to turn like a tank, but also drive diagonally like\
                      \ a crab. According to Electrek, this change could be Tesla's\
                      \ reaction to what its competitors do. Since the introduction\
                      \ of Tesla’s novelty, the market for electric pickup trucks\
                      \ has significantly evolved. Currently, one electric pickup\
                      \ on the market can turn like a tank – the Rivian R1T, while\
                      \ GMC's Hummer EV can drive diagonally. Following the announcement\
                      \ of Tesla Cybertruck in 2019, the company announced three configurations\
                      \ of the pickup truck: the entry-level model with one motor,\
                      \ the one with two motors, and the one with three. Rumor has\
                      \ it that the company intends to abandon the single-motor version\
                      \ altogether. In this case, Tesla Cybertruck will be sold with\
                      \ two, three, and four motors. Musk has promised to provide\
                      \ an update on the pickup's roadmap on the next earnings call.\
                      \ The production of Tesla Cybertruck is expected to begin at\
                      \ the end of 2022, and its mass production is slated to start\
                      \ in 2023."
                    url: https://internetprotocol.co/hitech/2021/12/07/tesla-to-release-a-four-motor-cybertruck/
                    image: https://internetprotocol.co/content/images/2021/12/Tesla-to-Release-a-Four-Motor-Version-of-Cybertruck.png
                    publish_date: 2022-09-30 01:07:48
                    author: Kay Lee
                    language: en
                    source_country: co
                    sentiment: 0.712523
              schema:
                $ref: '#/components/schemas/extractNews_200_response'
          description: Success
        "401":
          description: Unauthorized
        "402":
          description: Payment Required
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "406":
          description: Not Acceptable
        "429":
          description: Too Many Requests
      summary: Extract News
      tags:
      - News
  /extract-news-links:
    get:
      deprecated: false
      description: Extract news links from a news website.
      externalDocs:
        description: Read entire docs
        url: https://worldnewsapi.com/docs/extract-news-links/
      operationId: extractNewsLinks
      parameters:
      - description: The url of the news.
        explode: false
        in: query
        name: url
        required: true
        schema:
          example: https://www.bbc.com/news/world-us-canada-59340789
          maxLength: 1000
          pattern: "."
          type: string
        style: form
      - description: Whether to analyze the news (extract entities etc.)
        explode: false
        in: query
        name: analyze
        required: true
        schema:
          example: true
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              examples:
                Response:
                  value:
                    news_links:
                    - https://www.nytimes.com/2023/10/07/opinion/wnba-liberty-championship.html
                    - https://www.nytimes.com/2023/10/08/business/economy/labor-strikes.html
                    - https://www.nytimes.com/2023/10/08/dining/sunday-calls-for-old-fashioned-beef-stew.html
              schema:
                $ref: '#/components/schemas/extractNewsLinks_200_response'
          description: Success
        "401":
          description: Unauthorized
        "402":
          description: Payment Required
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "406":
          description: Not Acceptable
        "429":
          description: Too Many Requests
      summary: Extract News Links
      tags:
      - News
  /feed.rss:
    get:
      deprecated: false
      description: Turn a news website into an RSS feed. Any page of a news website
        can be turned into an RSS feed. Provide the URL to the page and the API will
        return an RSS feed with the latest news from that page.
      externalDocs:
        description: Read entire docs
        url: https://worldnewsapi.com/docs/website-to-rss-feed/
      operationId: newsWebsiteToRSSFeed
      parameters:
      - description: The url of the news.
        explode: false
        in: query
        name: url
        required: true
        schema:
          example: https://www.bbc.com/news/world-us-canada-59340789
          maxLength: 1000
          pattern: "."
          type: string
        style: form
      - description: Whether to analyze the news (extract entities etc.)
        explode: false
        in: query
        name: analyze
        required: true
        schema:
          example: true
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/xml:
              schema:
                type: object
          description: Success
        "401":
          description: Unauthorized
        "402":
          description: Payment Required
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "406":
          description: Not Acceptable
        "429":
          description: Too Many Requests
      summary: News Website to RSS Feed
      tags:
      - News
  /geo-coordinates:
    get:
      deprecated: false
      description: Retrieve the latitude and longitude of a location name. Given this
        information you can fill the location-filter parameter in the news search
        endpoint.
      externalDocs:
        description: Read entire docs
        url: https://worldnewsapi.com/docs/get-geo-coordinates/
      operationId: getGeoCoordinates
      parameters:
      - description: The address or name of the location.
        explode: false
        in: query
        name: location
        required: true
        schema:
          example: "Tokyo, Japan"
          maxLength: 1000
          pattern: "."
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              examples:
                Response:
                  value:
                    latitude: 35.652832
                    longitude: 139.839478
                    city: Tokyo
              schema:
                $ref: '#/components/schemas/getGeoCoordinates_200_response'
          description: Success
        "401":
          description: Unauthorized
        "402":
          description: Payment Required
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "406":
          description: Not Acceptable
        "429":
          description: Too Many Requests
      summary: Get Geo Coordinates
      tags:
      - News
components:
  schemas:
    searchNews_200_response_news_inner:
      example:
        summary: summary
        image: image
        sentiment: 5.962133916683182
        source_country: source_country
        language: language
        id: 5
        text: text
        title: title
        publish_date: publish_date
        url: url
        authors:
        - authors
        - authors
      properties:
        summary:
          nullable: true
          type: string
        image:
          nullable: true
          type: string
        sentiment:
          type: number
        source_country:
          nullable: true
          type: string
        language:
          nullable: true
          type: string
        id:
          type: integer
        text:
          nullable: true
          type: string
        title:
          nullable: true
          type: string
        publish_date:
          nullable: true
          type: string
        url:
          nullable: true
          type: string
        authors:
          items:
            nullable: true
            type: string
          type: array
      type: object
    searchNews_200_response:
      example:
        news:
        - summary: summary
          image: image
          sentiment: 5.962133916683182
          source_country: source_country
          language: language
          id: 5
          text: text
          title: title
          publish_date: publish_date
          url: url
          authors:
          - authors
          - authors
        - summary: summary
          image: image
          sentiment: 5.962133916683182
          source_country: source_country
          language: language
          id: 5
          text: text
          title: title
          publish_date: publish_date
          url: url
          authors:
          - authors
          - authors
        number: 6
        offset: 0
        available: 1
      properties:
        offset:
          type: integer
        number:
          type: integer
        available:
          type: integer
        news:
          items:
            $ref: '#/components/schemas/searchNews_200_response_news_inner'
          type: array
      type: object
    topNews_200_response_top_news_inner_news_inner:
      example:
        summary: summary
        image: image
        id: 0
        text: text
        title: title
        publish_date: publish_date
        url: url
        authors:
        - authors
        - authors
      properties:
        summary:
          nullable: true
          type: string
        image:
          nullable: true
          type: string
        id:
          type: integer
        text:
          nullable: true
          type: string
        title:
          nullable: true
          type: string
        publish_date:
          nullable: true
          type: string
        url:
          nullable: true
          type: string
        authors:
          items:
            nullable: true
            type: string
          type: array
      type: object
    topNews_200_response_top_news_inner:
      example:
        news:
        - summary: summary
          image: image
          id: 0
          text: text
          title: title
          publish_date: publish_date
          url: url
          authors:
          - authors
          - authors
        - summary: summary
          image: image
          id: 0
          text: text
          title: title
          publish_date: publish_date
          url: url
          authors:
          - authors
          - authors
      properties:
        news:
          items:
            $ref: '#/components/schemas/topNews_200_response_top_news_inner_news_inner'
          type: array
      type: object
    topNews_200_response:
      example:
        country: country
        top_news:
        - news:
          - summary: summary
            image: image
            id: 0
            text: text
            title: title
            publish_date: publish_date
            url: url
            authors:
            - authors
            - authors
          - summary: summary
            image: image
            id: 0
            text: text
            title: title
            publish_date: publish_date
            url: url
            authors:
            - authors
            - authors
        - news:
          - summary: summary
            image: image
            id: 0
            text: text
            title: title
            publish_date: publish_date
            url: url
            authors:
            - authors
            - authors
          - summary: summary
            image: image
            id: 0
            text: text
            title: title
            publish_date: publish_date
            url: url
            authors:
            - authors
            - authors
        language: language
      properties:
        top_news:
          items:
            $ref: '#/components/schemas/topNews_200_response_top_news_inner'
          type: array
        language:
          nullable: true
          type: string
        country:
          nullable: true
          type: string
      type: object
    extractNews_200_response:
      example:
        image: image
        sentiment: 0.8008281904610115
        source_country: source_country
        author: author
        language: language
        text: text
        title: title
        publish_date: publish_date
        url: url
      properties:
        title:
          nullable: true
          type: string
        text:
          nullable: true
          type: string
        url:
          nullable: true
          type: string
        image:
          nullable: true
          type: string
        publish_date:
          nullable: true
          type: string
        author:
          nullable: true
          type: string
        language:
          nullable: true
          type: string
        source_country:
          nullable: true
          type: string
        sentiment:
          type: number
      type: object
    extractNewsLinks_200_response:
      example:
        news_links:
        - news_links
        - news_links
      properties:
        news_links:
          items:
            nullable: true
            type: string
          type: array
      type: object
    getGeoCoordinates_200_response:
      example:
        city: city
        latitude: 0.8008281904610115
        longitude: 6.027456183070403
      properties:
        latitude:
          type: number
        longitude:
          type: number
        city:
          nullable: true
          type: string
      type: object
  securitySchemes:
    apiKey:
      in: query
      name: api-key
      type: apiKey
    headerApiKey:
      in: header
      name: x-api-key
      type: apiKey
